#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;35m'

CATVAL="$(sudo cat /proc/sys/net/ipv4/ip_forward)"

printf "  IP_FORWARD\n${CYAN}[0]${NC} - Desligar\n${CYAN}[1]${NC} - Acionar\n${CYAN}[2]${NC} - Status\nOpção: "

read USEROPT


if [ $USEROPT == 1 ]
then
	sudo echo 1 > /proc/sys/net/ipv4/ip_forward

	printf "${GREEN}[STATUS]${NC} [proc/sys/net/ipv4/ip_forward] = ${CATVAL}\n"
	exit 0

elif [ $USEROPT == 2 ]
then
	if [ $CATVAL == 0 ]
	then
		printf "${RED}[STATUS]${NC} /proc/sys/net/ipv4/ip_forward = ${CATVAL}\n"
	elif [ $CATVAL == 1 ]
	then
		printf "${GREEN}[STATUS]${NC} /proc/sys/net/ipv4/ip_forward] = ${CATVAL}\n"
		exit 0
	fi

elif [ $USEROPT == 0 ]
then
	sudo echo 0 > /proc/sys/net/ipv4/ip_forward
	printf "${RED}[STATUS]${NC} [proc/sys/net/ipv4/ip_forward] = ${CATVAL}\n"
	exit 0
else
	printf "${RED}[FAILED] ${NC}Opção: ${USEROPT} não existente.\n"
fi

